// SPDX-License-Identifier: GPL-3.0-or-later

pragma ComponentBehavior: Bound

import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.15

// Stitch-redesigned Hearing Aid setup page.
// Generated by Stitch (project "Linux AirPods Инфо", screen "Hearing
// Aid Setup") and re-implemented in QML.
//
// NOTE: this is a UI placeholder — the underlying hearing aid AAP
// commands are NOT wired into librepods Linux yet. Slider values are
// stored locally only. SAVE / RESET update local state. The page
// exists to demonstrate the design system across multiple screens.
Item {
    id: hearingRoot

    // External dependencies
    property var stackView: null
    property var iconFont: null

    // Stitch design system
    readonly property color primary: "#7bafff"
    readonly property color onSurface: "#ffffff"
    readonly property color onSurfaceVariant: "#adabaa"
    readonly property color glassColor: Qt.rgba(30 / 255, 30 / 255, 30 / 255, 0.55)
    readonly property color glassBorder: Qt.rgba(1, 1, 1, 0.06)
    readonly property color iconTileBg: "#262626"

    // Local hearing-aid model (placeholder, not yet wired to backend)
    property var audiogramL: [-15, -10, -25, -40, -30, -20]
    property var audiogramR: [-20, -12, -25, -35, -45, -20]
    property real amplification: 65
    property real balance: 0
    property real eqBass: 4
    property real eqLowMid: -2
    property real eqHighMid: 2
    property real eqTreble: 6
    property bool ambientNoiseReduction: true
    property bool conversationBoost: false
    property real ownVoiceAmp: 30

    // Top app bar
    Rectangle {
        id: appBar
        anchors.top: parent.top
        anchors.left: parent.left
        anchors.right: parent.right
        height: 60
        color: Qt.rgba(14 / 255, 14 / 255, 14 / 255, 0.85)

        Rectangle {
            anchors.bottom: parent.bottom
            anchors.left: parent.left
            anchors.right: parent.right
            height: 1
            color: Qt.rgba(1, 1, 1, 0.05)
        }

        Row {
            anchors.left: parent.left
            anchors.verticalCenter: parent.verticalCenter
            anchors.leftMargin: 18
            spacing: 14

            Rectangle {
                width: 36
                height: 36
                radius: 18
                color: backHover.containsMouse ? Qt.rgba(1, 1, 1, 0.08) : "transparent"

                Text {
                    anchors.centerIn: parent
                    text: "\u2190"
                    color: hearingRoot.primary
                    font.family: "Inter"
                    font.pixelSize: 20
                    font.bold: true
                }

                MouseArea {
                    id: backHover
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor
                    onClicked: if (hearingRoot.stackView) hearingRoot.stackView.pop()
                }
            }

            Text {
                anchors.verticalCenter: parent.verticalCenter
                text: "HEARING AID"
                color: hearingRoot.onSurface
                font.family: "Inter"
                font.pixelSize: 13
                font.bold: true
                font.letterSpacing: 2.4
            }
        }
    }

    // Footer with SAVE / RESET buttons (fixed at bottom)
    Rectangle {
        id: footer
        anchors.bottom: parent.bottom
        anchors.left: parent.left
        anchors.right: parent.right
        height: 110
        color: Qt.rgba(0, 0, 0, 0.75)

        ColumnLayout {
            anchors.fill: parent
            anchors.leftMargin: 22
            anchors.rightMargin: 22
            anchors.topMargin: 14
            anchors.bottomMargin: 14
            spacing: 8

            // Save profile (primary filled)
            Rectangle {
                Layout.fillWidth: true
                Layout.preferredHeight: 44
                radius: 14
                color: saveMa.containsMouse ? "#5ea2ff" : hearingRoot.primary

                Text {
                    anchors.centerIn: parent
                    text: qsTr("SAVE PROFILE")
                    color: "#002e5d"
                    font.family: "Inter"
                    font.pixelSize: 12
                    font.weight: Font.Black
                    font.letterSpacing: 1.6
                }

                MouseArea {
                    id: saveMa
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor
                    onClicked: console.log("Hearing aid profile saved (placeholder — no backend wiring yet)")
                }
            }

            // Reset (transparent secondary)
            Rectangle {
                Layout.fillWidth: true
                Layout.preferredHeight: 32
                radius: 12
                color: resetMa.containsMouse ? Qt.rgba(1, 1, 1, 0.05) : "transparent"

                Text {
                    anchors.centerIn: parent
                    text: qsTr("RESET")
                    color: hearingRoot.onSurfaceVariant
                    font.family: "Inter"
                    font.pixelSize: 11
                    font.bold: true
                    font.letterSpacing: 1.4
                }

                MouseArea {
                    id: resetMa
                    anchors.fill: parent
                    hoverEnabled: true
                    cursorShape: Qt.PointingHandCursor
                    onClicked: {
                        hearingRoot.audiogramL = [0, 0, 0, 0, 0, 0]
                        hearingRoot.audiogramR = [0, 0, 0, 0, 0, 0]
                        hearingRoot.amplification = 50
                        hearingRoot.balance = 0
                        hearingRoot.eqBass = 0
                        hearingRoot.eqLowMid = 0
                        hearingRoot.eqHighMid = 0
                        hearingRoot.eqTreble = 0
                    }
                }
            }
        }
    }

    // Scrollable content
    ScrollView {
        anchors.top: appBar.bottom
        anchors.left: parent.left
        anchors.right: parent.right
        anchors.bottom: footer.top
        clip: true
        ScrollBar.vertical.policy: ScrollBar.AsNeeded

        ColumnLayout {
            width: hearingRoot.width
            spacing: 22

            Item {
                Layout.fillWidth: true
                Layout.preferredHeight: 14
            }

            // ── AUDIOGRAM section ──────────────────────────────────
            ColumnLayout {
                Layout.fillWidth: true
                Layout.leftMargin: 22
                Layout.rightMargin: 22
                spacing: 12

                Text {
                    text: "AUDIOGRAM"
                    color: hearingRoot.onSurfaceVariant
                    font.family: "Inter"
                    font.pixelSize: 10
                    font.bold: true
                    font.letterSpacing: 1.8
                    leftPadding: 6
                }

                Rectangle {
                    Layout.fillWidth: true
                    Layout.preferredHeight: audioCol.implicitHeight + 36
                    radius: 24
                    color: hearingRoot.glassColor
                    border.width: 1
                    border.color: hearingRoot.glassBorder

                    ColumnLayout {
                        id: audioCol
                        anchors.fill: parent
                        anchors.leftMargin: 20
                        anchors.rightMargin: 20
                        anchors.topMargin: 16
                        anchors.bottomMargin: 16
                        spacing: 10

                        // Header row
                        RowLayout {
                            Layout.fillWidth: true

                            Text {
                                Layout.fillWidth: true
                                text: qsTr("FREQUENCY")
                                color: hearingRoot.onSurfaceVariant
                                font.family: "Inter"
                                font.pixelSize: 9
                                font.bold: true
                                font.letterSpacing: 1.4
                            }
                            Text {
                                Layout.preferredWidth: 80
                                horizontalAlignment: Text.AlignHCenter
                                text: "L"
                                color: hearingRoot.onSurfaceVariant
                                font.family: "Inter"
                                font.pixelSize: 9
                                font.bold: true
                                font.letterSpacing: 1.4
                            }
                            Text {
                                Layout.preferredWidth: 80
                                horizontalAlignment: Text.AlignHCenter
                                text: "R"
                                color: hearingRoot.onSurfaceVariant
                                font.family: "Inter"
                                font.pixelSize: 9
                                font.bold: true
                                font.letterSpacing: 1.4
                            }
                        }

                        // Frequency rows
                        Repeater {
                            model: ["250 Hz", "500 Hz", "1 kHz", "2 kHz", "4 kHz", "8 kHz"]
                            delegate: RowLayout {
                                required property int index
                                required property string modelData
                                Layout.fillWidth: true
                                spacing: 8

                                Text {
                                    Layout.fillWidth: true
                                    text: modelData
                                    color: Qt.rgba(1, 1, 1, 0.85)
                                    font.family: "Inter"
                                    font.pixelSize: 11
                                    font.weight: Font.Medium
                                }
                                Slider {
                                    Layout.preferredWidth: 80
                                    Layout.preferredHeight: 24
                                    from: -90
                                    to: 0
                                    value: hearingRoot.audiogramL[index]
                                    onValueChanged: {
                                        const arr = hearingRoot.audiogramL.slice();
                                        arr[index] = value;
                                        hearingRoot.audiogramL = arr;
                                    }
                                }
                                Slider {
                                    Layout.preferredWidth: 80
                                    Layout.preferredHeight: 24
                                    from: -90
                                    to: 0
                                    value: hearingRoot.audiogramR[index]
                                    onValueChanged: {
                                        const arr = hearingRoot.audiogramR.slice();
                                        arr[index] = value;
                                        hearingRoot.audiogramR = arr;
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // ── AMPLIFICATION section ──────────────────────────────
            ColumnLayout {
                Layout.fillWidth: true
                Layout.leftMargin: 22
                Layout.rightMargin: 22
                spacing: 12

                Text {
                    text: "AMPLIFICATION"
                    color: hearingRoot.onSurfaceVariant
                    font.family: "Inter"
                    font.pixelSize: 10
                    font.bold: true
                    font.letterSpacing: 1.8
                    leftPadding: 6
                }

                Rectangle {
                    Layout.fillWidth: true
                    Layout.preferredHeight: 80
                    radius: 24
                    color: hearingRoot.glassColor
                    border.width: 1
                    border.color: hearingRoot.glassBorder

                    RowLayout {
                        anchors.fill: parent
                        anchors.leftMargin: 22
                        anchors.rightMargin: 22
                        spacing: 18

                        Slider {
                            Layout.fillWidth: true
                            from: 0
                            to: 100
                            value: hearingRoot.amplification
                            onValueChanged: hearingRoot.amplification = value
                        }
                        Text {
                            text: Math.round(hearingRoot.amplification) + "%"
                            color: hearingRoot.primary
                            font.family: "Inter"
                            font.pixelSize: 28
                            font.weight: Font.Black
                            font.letterSpacing: -0.6
                        }
                    }
                }
            }

            // ── BALANCE section ────────────────────────────────────
            ColumnLayout {
                Layout.fillWidth: true
                Layout.leftMargin: 22
                Layout.rightMargin: 22
                spacing: 12

                Text {
                    text: "BALANCE"
                    color: hearingRoot.onSurfaceVariant
                    font.family: "Inter"
                    font.pixelSize: 10
                    font.bold: true
                    font.letterSpacing: 1.8
                    leftPadding: 6
                }

                Rectangle {
                    Layout.fillWidth: true
                    Layout.preferredHeight: 80
                    radius: 24
                    color: hearingRoot.glassColor
                    border.width: 1
                    border.color: hearingRoot.glassBorder

                    ColumnLayout {
                        anchors.fill: parent
                        anchors.leftMargin: 22
                        anchors.rightMargin: 22
                        anchors.topMargin: 12
                        anchors.bottomMargin: 12
                        spacing: 6

                        Slider {
                            Layout.fillWidth: true
                            from: -50
                            to: 50
                            value: hearingRoot.balance
                            onValueChanged: hearingRoot.balance = value
                        }
                        RowLayout {
                            Layout.fillWidth: true
                            Text {
                                text: "-L"
                                color: hearingRoot.onSurfaceVariant
                                font.family: "Inter"
                                font.pixelSize: 10
                                font.bold: true
                            }
                            Item { Layout.fillWidth: true }
                            Text {
                                text: "0"
                                color: hearingRoot.onSurfaceVariant
                                font.family: "Inter"
                                font.pixelSize: 10
                                font.bold: true
                            }
                            Item { Layout.fillWidth: true }
                            Text {
                                text: "R+"
                                color: hearingRoot.onSurfaceVariant
                                font.family: "Inter"
                                font.pixelSize: 10
                                font.bold: true
                            }
                        }
                    }
                }
            }

            // ── TONE section (4 vertical EQ bars) ──────────────────
            ColumnLayout {
                Layout.fillWidth: true
                Layout.leftMargin: 22
                Layout.rightMargin: 22
                spacing: 12

                Text {
                    text: "TONE"
                    color: hearingRoot.onSurfaceVariant
                    font.family: "Inter"
                    font.pixelSize: 10
                    font.bold: true
                    font.letterSpacing: 1.8
                    leftPadding: 6
                }

                Rectangle {
                    Layout.fillWidth: true
                    Layout.preferredHeight: 200
                    radius: 24
                    color: hearingRoot.glassColor
                    border.width: 1
                    border.color: hearingRoot.glassBorder

                    RowLayout {
                        anchors.fill: parent
                        anchors.margins: 22
                        spacing: 14

                        // Bass
                        ColumnLayout {
                            Layout.fillHeight: true
                            spacing: 8

                            Slider {
                                Layout.fillHeight: true
                                Layout.alignment: Qt.AlignHCenter
                                Layout.preferredWidth: 26
                                orientation: Qt.Vertical
                                from: -12
                                to: 12
                                value: hearingRoot.eqBass
                                onValueChanged: hearingRoot.eqBass = value
                            }
                            Text {
                                Layout.alignment: Qt.AlignHCenter
                                text: "BASS"
                                color: hearingRoot.onSurfaceVariant
                                font.family: "Inter"
                                font.pixelSize: 9
                                font.bold: true
                                font.letterSpacing: 1.0
                            }
                        }
                        // Low-Mid
                        ColumnLayout {
                            Layout.fillHeight: true
                            spacing: 8
                            Slider {
                                Layout.fillHeight: true
                                Layout.alignment: Qt.AlignHCenter
                                Layout.preferredWidth: 26
                                orientation: Qt.Vertical
                                from: -12
                                to: 12
                                value: hearingRoot.eqLowMid
                                onValueChanged: hearingRoot.eqLowMid = value
                            }
                            Text {
                                Layout.alignment: Qt.AlignHCenter
                                text: "LOW-MID"
                                color: hearingRoot.onSurfaceVariant
                                font.family: "Inter"
                                font.pixelSize: 9
                                font.bold: true
                                font.letterSpacing: 1.0
                            }
                        }
                        // High-Mid
                        ColumnLayout {
                            Layout.fillHeight: true
                            spacing: 8
                            Slider {
                                Layout.fillHeight: true
                                Layout.alignment: Qt.AlignHCenter
                                Layout.preferredWidth: 26
                                orientation: Qt.Vertical
                                from: -12
                                to: 12
                                value: hearingRoot.eqHighMid
                                onValueChanged: hearingRoot.eqHighMid = value
                            }
                            Text {
                                Layout.alignment: Qt.AlignHCenter
                                text: "HIGH-MID"
                                color: hearingRoot.onSurfaceVariant
                                font.family: "Inter"
                                font.pixelSize: 9
                                font.bold: true
                                font.letterSpacing: 1.0
                            }
                        }
                        // Treble
                        ColumnLayout {
                            Layout.fillHeight: true
                            spacing: 8
                            Slider {
                                Layout.fillHeight: true
                                Layout.alignment: Qt.AlignHCenter
                                Layout.preferredWidth: 26
                                orientation: Qt.Vertical
                                from: -12
                                to: 12
                                value: hearingRoot.eqTreble
                                onValueChanged: hearingRoot.eqTreble = value
                            }
                            Text {
                                Layout.alignment: Qt.AlignHCenter
                                text: "TREBLE"
                                color: hearingRoot.onSurfaceVariant
                                font.family: "Inter"
                                font.pixelSize: 9
                                font.bold: true
                                font.letterSpacing: 1.0
                            }
                        }
                    }
                }
            }

            // ── AMBIENT section ────────────────────────────────────
            ColumnLayout {
                Layout.fillWidth: true
                Layout.leftMargin: 22
                Layout.rightMargin: 22
                spacing: 12

                Text {
                    text: "AMBIENT"
                    color: hearingRoot.onSurfaceVariant
                    font.family: "Inter"
                    font.pixelSize: 10
                    font.bold: true
                    font.letterSpacing: 1.8
                    leftPadding: 6
                }

                Rectangle {
                    Layout.fillWidth: true
                    radius: 24
                    color: hearingRoot.glassColor
                    border.width: 1
                    border.color: hearingRoot.glassBorder

                    ColumnLayout {
                        anchors.fill: parent
                        spacing: 0

                        SettingRow {
                            label: qsTr("Ambient Noise Reduction")
                            iconText: "\u29D7"
                            type: "toggle"
                            toggleChecked: hearingRoot.ambientNoiseReduction
                            onToggleClicked: hearingRoot.ambientNoiseReduction = !toggleChecked
                        }
                        Rectangle { Layout.fillWidth: true; Layout.preferredHeight: 1; color: Qt.rgba(1, 1, 1, 0.04) }

                        SettingRow {
                            label: qsTr("Conversation Boost")
                            iconText: "\u2B25"
                            type: "toggle"
                            toggleChecked: hearingRoot.conversationBoost
                            onToggleClicked: hearingRoot.conversationBoost = !toggleChecked
                        }
                        Rectangle { Layout.fillWidth: true; Layout.preferredHeight: 1; color: Qt.rgba(1, 1, 1, 0.04) }

                        // Own voice amp row
                        ColumnLayout {
                            Layout.fillWidth: true
                            Layout.leftMargin: 18
                            Layout.rightMargin: 18
                            Layout.topMargin: 14
                            Layout.bottomMargin: 14
                            spacing: 10

                            RowLayout {
                                Layout.fillWidth: true
                                spacing: 14

                                Rectangle {
                                    Layout.preferredWidth: 44
                                    Layout.preferredHeight: 44
                                    radius: 14
                                    color: hearingRoot.iconTileBg
                                    Text {
                                        anchors.centerIn: parent
                                        text: "\u266B"
                                        color: hearingRoot.primary
                                        font.family: "Inter"
                                        font.pixelSize: 18
                                        font.bold: true
                                    }
                                }
                                Text {
                                    Layout.fillWidth: true
                                    text: qsTr("Own Voice Amplification")
                                    color: hearingRoot.onSurface
                                    font.family: "Inter"
                                    font.pixelSize: 13
                                    font.weight: Font.Medium
                                }
                                Text {
                                    text: Math.round(hearingRoot.ownVoiceAmp) + "%"
                                    color: hearingRoot.primary
                                    font.family: "Inter"
                                    font.pixelSize: 12
                                    font.bold: true
                                }
                            }
                            Slider {
                                Layout.fillWidth: true
                                from: 0
                                to: 100
                                value: hearingRoot.ownVoiceAmp
                                onValueChanged: hearingRoot.ownVoiceAmp = value
                            }
                        }
                    }
                }
            }

            Item {
                Layout.fillWidth: true
                Layout.preferredHeight: 14
            }
        }
    }
}
