pragma ComponentBehavior: Bound

import QtQuick 2.15
import QtQuick.Controls 2.15
import QtQuick.Layouts 1.15
import QtQuick.Effects

// Stitch-redesigned Settings page.
// Generated by Stitch (project "Linux AirPods Инфо", screen
// "LinuxPods Settings Final") and re-implemented in QML.
//
// Layout: top app bar → AirPods hero → GENERAL / EAR DETECTION /
// CONNECTION / ADVANCED sections, each a glass card.
Item {
    id: settingsRoot

    // External dependencies (set from Main.qml)
    property var stackView: null
    property var iconFont: null
    property var keysQrDialog: null

    // Stitch design system
    readonly property color primary: "#7bafff"
    readonly property color onSurface: "#ffffff"
    readonly property color onSurfaceVariant: "#adabaa"
    readonly property color glassColor: Qt.rgba(30 / 255, 30 / 255, 30 / 255, 0.55)
    readonly property color glassBorder: Qt.rgba(1, 1, 1, 0.06)
    readonly property color inputBg: "#131313"
    readonly property color iconTileBg: "#262626"

    // Top app bar — Stitch h-16 (64px) bg #131313/80 backdrop-blur
    Rectangle {
        id: appBar
        anchors.top: parent.top
        anchors.left: parent.left
        anchors.right: parent.right
        height: 64
        color: Qt.rgba(19 / 255, 19 / 255, 19 / 255, 0.50)

        Rectangle {
            anchors.bottom: parent.bottom
            anchors.left: parent.left
            anchors.right: parent.right
            height: 1
            color: Qt.rgba(1, 1, 1, 0.05)
        }

        // Back button
        Rectangle {
            anchors.left: parent.left
            anchors.verticalCenter: parent.verticalCenter
            anchors.leftMargin: 18
            width: 36
            height: 36
            radius: 18
            color: backHover.containsMouse ? Qt.rgba(1, 1, 1, 0.08) : "transparent"

            Text {
                anchors.centerIn: parent
                text: "\u2190"
                color: settingsRoot.primary
                font.family: "Inter"
                font.pixelSize: 20
                font.bold: true
            }

            MouseArea {
                id: backHover
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: if (settingsRoot.stackView) settingsRoot.stackView.pop()
            }
        }

        // Title centered (Stitch text-base = 16px tracking-widest)
        Text {
            anchors.centerIn: parent
            text: "SETTINGS"
            color: settingsRoot.onSurface
            font.family: "Inter"
            font.pixelSize: 16
            font.weight: Font.DemiBold
            font.letterSpacing: 2.0
        }
    }

    // Scrollable content
    ScrollView {
        anchors.top: appBar.bottom
        anchors.left: parent.left
        anchors.right: parent.right
        anchors.bottom: parent.bottom
        clip: true
        ScrollBar.vertical.policy: ScrollBar.AsNeeded

        ColumnLayout {
            width: settingsRoot.width
            spacing: 22

            // ── Hero with real Gaussian blur glow ───────────────────
            Item {
                Layout.fillWidth: true
                Layout.preferredHeight: 220
                Layout.topMargin: 18

                Rectangle {
                    id: settingsGlowSource
                    anchors.centerIn: parent
                    anchors.verticalCenterOffset: -22
                    width: 140
                    height: 140
                    radius: width / 2
                    color: settingsRoot.primary
                    visible: false
                    layer.enabled: true
                }

                MultiEffect {
                    anchors.centerIn: parent
                    anchors.verticalCenterOffset: -22
                    width: 280
                    height: 280
                    source: settingsGlowSource
                    blurEnabled: true
                    blur: 1.0
                    blurMax: 96
                    blurMultiplier: 1.4
                    opacity: 0.5
                    autoPaddingEnabled: true
                }

                Image {
                    anchors.centerIn: parent
                    anchors.verticalCenterOffset: -22
                    source: "qrc:/icons/assets/airpods.png"
                    width: 140
                    height: 140
                    fillMode: Image.PreserveAspectFit
                    mipmap: true
                    smooth: true
                }

                Column {
                    anchors.bottom: parent.bottom
                    anchors.horizontalCenter: parent.horizontalCenter
                    spacing: 2

                    Text {
                        anchors.horizontalCenter: parent.horizontalCenter
                        text: airPodsTrayApp.deviceInfo.deviceName || "LinuxPods Pro"
                        color: settingsRoot.onSurface
                        font.family: "Inter"
                        font.pixelSize: 22
                        font.weight: Font.ExtraBold
                        font.letterSpacing: -0.4
                    }
                    Text {
                        anchors.horizontalCenter: parent.horizontalCenter
                        text: "v0.1.0 (LinuxPods build)"
                        color: settingsRoot.onSurfaceVariant
                        font.family: "Inter"
                        font.pixelSize: 11
                    }
                }
            }

            // ── GENERAL section ─────────────────────────────────────
            ColumnLayout {
                Layout.fillWidth: true
                Layout.leftMargin: 22
                Layout.rightMargin: 22
                spacing: 12

                Text {
                    text: "GENERAL"
                    color: settingsRoot.onSurfaceVariant
                    font.family: "Inter"
                    font.pixelSize: 10
                    font.bold: true
                    font.letterSpacing: 1.8
                    leftPadding: 6
                }

                Rectangle {
                    Layout.fillWidth: true
                    Layout.preferredHeight: generalCol.implicitHeight
                    radius: 24
                    color: settingsRoot.glassColor
                    border.width: 1
                    border.color: settingsRoot.glassBorder

                    ColumnLayout {
                        id: generalCol
                        anchors.left: parent.left
                        anchors.right: parent.right
                        anchors.top: parent.top
                        spacing: 0

                        SettingRow {
                            label: qsTr("Auto-start on login")
                            iconText: "\u279C"
                            type: "toggle"
                            toggleChecked: airPodsTrayApp.autoStartManager.autoStartEnabled
                            onToggleClicked: airPodsTrayApp.autoStartManager.autoStartEnabled = !toggleChecked
                        }
                        Rectangle { Layout.fillWidth: true; Layout.preferredHeight: 1; color: Qt.rgba(1, 1, 1, 0.04) }

                        SettingRow {
                            label: qsTr("System notifications")
                            iconText: "\u26A0"
                            type: "toggle"
                            toggleChecked: airPodsTrayApp.notificationsEnabled
                            onToggleClicked: airPodsTrayApp.notificationsEnabled = !toggleChecked
                        }
                        Rectangle { Layout.fillWidth: true; Layout.preferredHeight: 1; color: Qt.rgba(1, 1, 1, 0.04) }

                        SettingRow {
                            label: qsTr("Cross-device with Android")
                            iconText: "\u29BF"
                            type: "toggle"
                            toggleChecked: airPodsTrayApp.crossDeviceEnabled
                            onToggleClicked: airPodsTrayApp.setCrossDeviceEnabled(!toggleChecked)
                        }
                    }
                }
            }

            // ── EAR DETECTION section ───────────────────────────────
            ColumnLayout {
                Layout.fillWidth: true
                Layout.leftMargin: 22
                Layout.rightMargin: 22
                spacing: 12

                Text {
                    text: "EAR DETECTION"
                    color: settingsRoot.onSurfaceVariant
                    font.family: "Inter"
                    font.pixelSize: 10
                    font.bold: true
                    font.letterSpacing: 1.8
                    leftPadding: 6
                }

                Rectangle {
                    Layout.fillWidth: true
                    Layout.preferredHeight: earCol.implicitHeight + 30
                    radius: 24
                    color: settingsRoot.glassColor
                    border.width: 1
                    border.color: settingsRoot.glassBorder

                    ColumnLayout {
                        id: earCol
                        anchors.left: parent.left
                        anchors.right: parent.right
                        anchors.top: parent.top
                        anchors.leftMargin: 18
                        anchors.rightMargin: 18
                        anchors.topMargin: 16
                        spacing: 14

                        // Pause behavior — icon row + segmented control
                        RowLayout {
                            Layout.fillWidth: true
                            spacing: 14

                            Rectangle {
                                Layout.preferredWidth: 44
                                Layout.preferredHeight: 44
                                radius: 14
                                color: settingsRoot.iconTileBg
                                Text {
                                    anchors.centerIn: parent
                                    text: "\u23F8"
                                    color: settingsRoot.primary
                                    font.family: "Inter"
                                    font.pixelSize: 18
                                    font.bold: true
                                }
                            }
                            Text {
                                Layout.fillWidth: true
                                text: qsTr("Pause behavior")
                                color: settingsRoot.onSurface
                                font.family: "Inter"
                                font.pixelSize: 13
                                font.weight: Font.Medium
                            }
                        }

                        SegmentedControl {
                            Layout.fillWidth: true
                            Layout.preferredHeight: 38
                            model: [qsTr("ONE"), qsTr("BOTH"), qsTr("NEVER")]
                            currentIndex: airPodsTrayApp.earDetectionBehavior
                            onCurrentIndexChanged: airPodsTrayApp.earDetectionBehavior = currentIndex
                        }

                        Rectangle { Layout.fillWidth: true; Layout.preferredHeight: 1; color: Qt.rgba(1, 1, 1, 0.04) }

                        // One bud ANC
                        SettingRow {
                            label: qsTr("One bud ANC mode")
                            iconText: "\u266B"
                            type: "toggle"
                            toggleChecked: airPodsTrayApp.deviceInfo.oneBudANCMode
                            onToggleClicked: airPodsTrayApp.deviceInfo.oneBudANCMode = !toggleChecked
                        }
                    }
                }
            }

            // ── CONNECTION section ──────────────────────────────────
            ColumnLayout {
                Layout.fillWidth: true
                Layout.leftMargin: 22
                Layout.rightMargin: 22
                spacing: 12

                Text {
                    text: "CONNECTION"
                    color: settingsRoot.onSurfaceVariant
                    font.family: "Inter"
                    font.pixelSize: 10
                    font.bold: true
                    font.letterSpacing: 1.8
                    leftPadding: 6
                }

                Rectangle {
                    Layout.fillWidth: true
                    Layout.preferredHeight: connCol.implicitHeight + 32
                    radius: 24
                    color: settingsRoot.glassColor
                    border.width: 1
                    border.color: settingsRoot.glassBorder

                    ColumnLayout {
                        id: connCol
                        anchors.left: parent.left
                        anchors.right: parent.right
                        anchors.top: parent.top
                        anchors.leftMargin: 18
                        anchors.rightMargin: 18
                        anchors.topMargin: 16
                        spacing: 16

                        // Retry attempts row
                        RowLayout {
                            Layout.fillWidth: true
                            spacing: 14

                            Rectangle {
                                Layout.preferredWidth: 44
                                Layout.preferredHeight: 44
                                radius: 14
                                color: settingsRoot.iconTileBg
                                Text {
                                    anchors.centerIn: parent
                                    text: "\u21BB"
                                    color: settingsRoot.primary
                                    font.family: "Inter"
                                    font.pixelSize: 18
                                    font.bold: true
                                }
                            }
                            ColumnLayout {
                                Layout.fillWidth: true
                                spacing: 2
                                Text {
                                    text: qsTr("Retry attempts")
                                    color: settingsRoot.onSurface
                                    font.family: "Inter"
                                    font.pixelSize: 13
                                    font.weight: Font.Medium
                                }
                                Text {
                                    text: qsTr("BT protocol fallback")
                                    color: settingsRoot.onSurfaceVariant
                                    font.family: "Inter"
                                    font.pixelSize: 10
                                }
                            }
                            // Stepper
                            Rectangle {
                                Layout.preferredWidth: 110
                                Layout.preferredHeight: 36
                                radius: 12
                                color: settingsRoot.inputBg

                                RowLayout {
                                    anchors.fill: parent
                                    anchors.margins: 4
                                    spacing: 0

                                    Rectangle {
                                        Layout.preferredWidth: 28
                                        Layout.fillHeight: true
                                        radius: 8
                                        color: minusMa.containsMouse ? Qt.rgba(1, 1, 1, 0.05) : "transparent"
                                        Text {
                                            anchors.centerIn: parent
                                            text: "\u2212"
                                            color: settingsRoot.onSurface
                                            font.pixelSize: 16
                                            font.bold: true
                                        }
                                        MouseArea {
                                            id: minusMa
                                            anchors.fill: parent
                                            hoverEnabled: true
                                            cursorShape: Qt.PointingHandCursor
                                            onClicked: if (airPodsTrayApp.retryAttempts > 1) airPodsTrayApp.retryAttempts = airPodsTrayApp.retryAttempts - 1
                                        }
                                    }
                                    Text {
                                        Layout.fillWidth: true
                                        horizontalAlignment: Text.AlignHCenter
                                        text: airPodsTrayApp.retryAttempts
                                        color: settingsRoot.primary
                                        font.family: "Inter"
                                        font.pixelSize: 14
                                        font.bold: true
                                    }
                                    Rectangle {
                                        Layout.preferredWidth: 28
                                        Layout.fillHeight: true
                                        radius: 8
                                        color: plusMa.containsMouse ? Qt.rgba(1, 1, 1, 0.05) : "transparent"
                                        Text {
                                            anchors.centerIn: parent
                                            text: "+"
                                            color: settingsRoot.onSurface
                                            font.pixelSize: 16
                                            font.bold: true
                                        }
                                        MouseArea {
                                            id: plusMa
                                            anchors.fill: parent
                                            hoverEnabled: true
                                            cursorShape: Qt.PointingHandCursor
                                            onClicked: if (airPodsTrayApp.retryAttempts < 10) airPodsTrayApp.retryAttempts = airPodsTrayApp.retryAttempts + 1
                                        }
                                    }
                                }
                            }
                        }

                        Rectangle { Layout.fillWidth: true; Layout.preferredHeight: 1; color: Qt.rgba(1, 1, 1, 0.04) }

                        // Rename row
                        ColumnLayout {
                            Layout.fillWidth: true
                            spacing: 8

                            RowLayout {
                                Layout.fillWidth: true
                                spacing: 14
                                Rectangle {
                                    Layout.preferredWidth: 44
                                    Layout.preferredHeight: 44
                                    radius: 14
                                    color: settingsRoot.iconTileBg
                                    Text {
                                        anchors.centerIn: parent
                                        text: "\u270E"
                                        color: settingsRoot.primary
                                        font.family: "Inter"
                                        font.pixelSize: 18
                                        font.bold: true
                                    }
                                }
                                Text {
                                    Layout.fillWidth: true
                                    text: qsTr("Rename AirPods")
                                    color: settingsRoot.onSurface
                                    font.family: "Inter"
                                    font.pixelSize: 13
                                    font.weight: Font.Medium
                                }
                            }
                            TextField {
                                id: renameField
                                Layout.fillWidth: true
                                placeholderText: airPodsTrayApp.deviceInfo.deviceName || "LinuxPods Pro"
                                color: settingsRoot.onSurface
                                font.family: "Inter"
                                font.pixelSize: 12
                                background: Rectangle {
                                    radius: 14
                                    color: settingsRoot.inputBg
                                    border.width: renameField.activeFocus ? 1 : 0
                                    border.color: settingsRoot.primary
                                }
                                onAccepted: airPodsTrayApp.renameAirPods(text)
                            }
                        }

                        Rectangle { Layout.fillWidth: true; Layout.preferredHeight: 1; color: Qt.rgba(1, 1, 1, 0.04) }

                        // Phone MAC row
                        ColumnLayout {
                            Layout.fillWidth: true
                            spacing: 8

                            RowLayout {
                                Layout.fillWidth: true
                                spacing: 14
                                Rectangle {
                                    Layout.preferredWidth: 44
                                    Layout.preferredHeight: 44
                                    radius: 14
                                    color: settingsRoot.iconTileBg
                                    Text {
                                        anchors.centerIn: parent
                                        text: "\u2726"
                                        color: settingsRoot.primary
                                        font.family: "Inter"
                                        font.pixelSize: 18
                                        font.bold: true
                                    }
                                }
                                Text {
                                    Layout.fillWidth: true
                                    text: qsTr("Phone MAC address")
                                    color: settingsRoot.onSurface
                                    font.family: "Inter"
                                    font.pixelSize: 13
                                    font.weight: Font.Medium
                                }
                            }
                            TextField {
                                id: macField
                                Layout.fillWidth: true
                                placeholderText: (PHONE_MAC_ADDRESS !== "" ? PHONE_MAC_ADDRESS : "00:00:00:00:00:00")
                                color: settingsRoot.onSurface
                                font.family: "monospace"
                                font.pixelSize: 12
                                background: Rectangle {
                                    radius: 14
                                    color: settingsRoot.inputBg
                                    border.width: macField.activeFocus ? 1 : 0
                                    border.color: settingsRoot.primary
                                }
                                onAccepted: airPodsTrayApp.setPhoneMac(text)
                            }
                        }
                    }
                }
            }

            // ── ADVANCED section ────────────────────────────────────
            ColumnLayout {
                Layout.fillWidth: true
                Layout.leftMargin: 22
                Layout.rightMargin: 22
                spacing: 12

                Text {
                    text: "ADVANCED"
                    color: settingsRoot.onSurfaceVariant
                    font.family: "Inter"
                    font.pixelSize: 10
                    font.bold: true
                    font.letterSpacing: 1.8
                    leftPadding: 6
                }

                Rectangle {
                    Layout.fillWidth: true
                    Layout.preferredHeight: 80
                    radius: 24
                    color: settingsRoot.glassColor
                    border.width: 1
                    border.color: settingsRoot.glassBorder

                    SettingRow {
                        anchors.fill: parent
                        label: qsTr("Magic Cloud Keys QR")
                        sublabel: qsTr("Sync cross-platform identifiers")
                        iconText: "\u29C9"
                        iconColor: "#eda8ff"
                        type: "chevron"
                        clickable: true
                        onRowClicked: if (settingsRoot.keysQrDialog) settingsRoot.keysQrDialog.show()
                    }
                }
            }

            // Footer pill
            Item {
                Layout.fillWidth: true
                Layout.topMargin: 8
                Layout.preferredHeight: 36

                Rectangle {
                    anchors.centerIn: parent
                    width: kernelRow.implicitWidth + 28
                    height: 28
                    radius: 14
                    color: Qt.rgba(38 / 255, 38 / 255, 38 / 255, 0.6)

                    Row {
                        id: kernelRow
                        anchors.centerIn: parent
                        spacing: 8

                        Rectangle {
                            anchors.verticalCenter: parent.verticalCenter
                            width: 8
                            height: 8
                            radius: 4
                            color: "#70f9af"
                        }
                        Text {
                            anchors.verticalCenter: parent.verticalCenter
                            text: qsTr("KERNEL LINK ACTIVE")
                            color: settingsRoot.onSurfaceVariant
                            font.family: "Inter"
                            font.pixelSize: 9
                            font.bold: true
                            font.letterSpacing: 1.6
                        }
                    }
                }
            }

            Item {
                Layout.fillWidth: true
                Layout.preferredHeight: 24
            }
        }
    }
}
